### ISSUE TITLE
Multiple Connections!

### ISSUE THREAD

**Issue by DHidee66** [exponentjs/xde#35]
Hey,

Is it possible not to deliver the app as a single big bundle? If we have many js files in the system for each component and a main common file can they talk with each other. I came across to this project https://github.com/zoubin/react-native-factor-bundle and I wondered what would you guys think about it.

Thank You!

**Comment by ide** [comment]
We will probably build something like bundle splitting for Exponent but I don't think there would be a big benefit right now. Our server supports serving only one bundle at a time anyway.

That factor project looks like it is for plain RN apps where you have control over the native code that does the bundle loading and you are trying to embed two RN apps in the same IPA. To do that I would just create a JS file with two AppRegistry entries instead of using that factor tool, but again a Exponent isn't designed for that. Could you clarify your use case more.

**Comment by DHidee66** [comment]
I was wondering how to make bundle updates more efficient. If we had a main bundle with the common code and some components in different files then we could just update the components. 
But then there is the issue if the main bundle can talk with other compiled js files in the system.

**Comment by ide** [comment]
Bundle splitting is something that people are thinking about but I think it just hasn't been that important. With gzip compression the bundle goes down to 500KB or so.

**Comment by DHidee66** [comment]
Do you think what is holding it back is the communication between bundles inside the system?
